[connections.my_database]
    type="sql"
    dialect="sql"
    username="NcxPerso"
    password="NcxPerso"
    host="172.22.0.144" # IP or URL
    port=3314 # Port number
    database="NanoPerso_OAB" # Database name